apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 409261535226.dkr.ecr.ap-east-1.amazonaws.com/demo-frontend
  newName: 409261535226.dkr.ecr.ap-east-1.amazonaws.com/demo-frontend
  newTag: f764f918
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
